# Vulture dead-code allowlist (the CI dead-code gate: `make deadcode`).
# These names are referenced in ways vulture's static scan of the runtime package cannot
# see: FastAPI route handlers (registered via decorators), dataclass fields read via
# asdict(), framework-override methods/attributes, the retained v0.2.0 device_affinity
# shim, and methods exercised only from the test suite. Regenerate with:
#   python -m vulture netcorenoc --make-whitelist > vulture_allowlist.py

_.capture_signals  # unused method (netcorenoc/api.py:148)
security_headers  # unused function (netcorenoc/api.py:177)
healthz  # unused function (netcorenoc/api.py:284)
readyz  # unused function (netcorenoc/api.py:288)
_.status_code  # unused attribute (netcorenoc/api.py:304)
login  # unused function (netcorenoc/api.py:324)
logout  # unused function (netcorenoc/api.py:393)
me  # unused function (netcorenoc/api.py:406)
change_password  # unused function (netcorenoc/api.py:414)
graph  # unused function (netcorenoc/api.py:466)
classes  # unused function (netcorenoc/api.py:472)
situations  # unused function (netcorenoc/api.py:477)
situation  # unused function (netcorenoc/api.py:484)
timeline  # unused function (netcorenoc/api.py:492)
entities  # unused function (netcorenoc/api.py:502)
entity_detail  # unused function (netcorenoc/api.py:512)
state_clears  # unused function (netcorenoc/api.py:545)
feedback  # unused function (netcorenoc/api.py:586)
change_role  # unused function (netcorenoc/api.py:678)
get_config  # unused function (netcorenoc/api.py:771)
set_config  # unused function (netcorenoc/api.py:783)
read_quarantine  # unused function (netcorenoc/api.py:809)
read_audit  # unused function (netcorenoc/api.py:828)
export_audit  # unused function (netcorenoc/api.py:838)
events  # unused function (netcorenoc/api.py:877)
varbind_name  # unused function (netcorenoc/known_oids.py:195)
_.device_affinity  # unused method (netcorenoc/learn.py:336)
_.msg  # unused attribute (netcorenoc/logsetup.py:37)
_.format  # unused method (netcorenoc/logsetup.py:53)
_.handlers  # unused attribute (netcorenoc/logsetup.py:76)
_.processed  # unused attribute (netcorenoc/main.py:225)
_.processed  # unused attribute (netcorenoc/main.py:368)
_.should_exit  # unused attribute (netcorenoc/main.py:907)
PUBLIC_ROUTES  # unused variable (netcorenoc/rbac.py:79)
received  # unused variable (netcorenoc/receiver.py:51)
accepted  # unused variable (netcorenoc/receiver.py:52)
denied  # unused variable (netcorenoc/receiver.py:53)
quarantined  # unused variable (netcorenoc/receiver.py:54)
_.datagram_received  # unused method (netcorenoc/receiver.py:299)
_.received  # unused attribute (netcorenoc/receiver.py:301)
_.denied  # unused attribute (netcorenoc/receiver.py:303)
_.accepted  # unused attribute (netcorenoc/receiver.py:308)
_.quarantined  # unused attribute (netcorenoc/receiver.py:311)
_.row_factory  # unused attribute (netcorenoc/store.py:80)
_.entity_count_for_ne  # unused method (netcorenoc/store.py:627)
_.set_must_change_password  # unused method (netcorenoc/store.py:852)
_.best_promotable  # unused method (netcorenoc/varbind_profile.py:345)

# v0.6.0 — the scoring seam. FastAPI route handlers (registered by decorator, never called by
# name) and the reserved/read-by-scorer LinkFeatures fields. The reserved slots are deliberately
# unread in v0.6.0: they exist so v0.7/v0.8 features are a minor contract bump rather than a
# breaking change (DECISIONS #49), and `tests/test_scoring.py` asserts they stay None and are
# ignored. `class_i`/`class_j`/`ne_i`/`ne_j` are carried for future scorers and for provenance;
# the built-in AdditiveScorer scores on the affinities already resolved from them.
get_scorer  # unused function (netcorenoc/api.py:890)
preview_scorer  # unused function (netcorenoc/api.py:930)
set_scorer  # unused function (netcorenoc/api.py:1003)
rollback_scorer  # unused function (netcorenoc/api.py:1062)
class_i  # unused variable (netcorenoc/scoring.py:78)
class_j  # unused variable (netcorenoc/scoring.py:79)
ne_i  # unused variable (netcorenoc/scoring.py:81)
ne_j  # unused variable (netcorenoc/scoring.py:82)
severity_i  # unused variable (netcorenoc/scoring.py:86)
severity_j  # unused variable (netcorenoc/scoring.py:87)
topo_distance  # unused variable (netcorenoc/scoring.py:88)
probable_cause_i  # unused variable (netcorenoc/scoring.py:89)
probable_cause_j  # unused variable (netcorenoc/scoring.py:90)
event_type_i  # unused variable (netcorenoc/scoring.py:91)
event_type_j  # unused variable (netcorenoc/scoring.py:92)
