/* Judge → every model on one axis (v0.27.0, ADR #427).
 *
 * The comparisons that are fair to draw together, and only those: every model in the league was
 * trained on the same rows, tuned on the same validation streams and measured on the same test
 * streams, over the same feature vector. So the curves overlay — ROC, precision–recall, reliability,
 * and the search's best-so-far validation loss — and the per-model numbers share a scale.
 *
 * What is **not** overlaid: a hyperparameter's axis (each family has its own) and the train ×
 * validation curve (each family's capacity axis is different — rounds, trees, depth, iterations).
 * Those stay on the per-model view.
 *
 * Each model keeps one colour on every chart and its name is in every legend, so no reading rests
 * on colour alone.
 */

import { html } from "../../dom.js";
import { Bars } from "../../compare.js";
import { Legend } from "../../charts.js";
import { Curve, Scatter } from "../../modelcharts.js";
import { GEN, suiteRows } from "./leaguecharts.js";

const VALID = "generated data, validation streams";

/** One colour per model, in league order: `chart-m0` … `chart-m4` in the stylesheet. */
export const toneOf = (index) => `m${index % 5}`;

function iidPairs(model) {
  return (model.pairs || {}).test_iid || {};
}

function bestSoFar(trials) {
  let low = Infinity;
  return trials.filter((t) => t.valid_loss != null).map((t, i) => {
    low = Math.min(low, t.valid_loss);
    return [i + 1, low];
  });
}

export function CompareCharts({ models }) {
  const trained = (models || []).filter((m) => m.origin !== "site");
  if (!trained.length) {
    return html`<p class="hint">No pre-trained model is loaded, so there is nothing to compare.</p>`;
  }
  const legend = trained.map((m, i) => ({ name: m.name, tone: toneOf(i) }));
  const curve = (pick) => trained.map((m, i) => ({ name: m.name, tone: toneOf(i), points: pick(m) }));
  const n = trained.map((m) => iidPairs(m).pairs).filter(Boolean)[0];
  const span = n ? `${n} pairs per model, the same pairs for every one` : "";
  return html`<div class="league-compare">
    <${Legend} series=${legend} />
    <div class="judge-grid">
      <${Bars} title="3 · Model performance — mean pairwise F1 over the five suites" max=${1} unit="ratio"
        rows=${trained.map((m, i) => ({ key: m.ref, label: m.name, value: meanF1(m), tone: toneOf(i) }))}
        source=${`${GEN} and the hand-labelled corpus`} span="the judge's offline score"
        note="higher is better; the judge ranks by this, ties by fewer repair gestures" />
      <${Bars} title="3 · Hand-labelled corpus — pairwise F1" max=${1} unit="ratio"
        rows=${trained.map((m, i) => ({ key: m.ref, label: m.name,
          value: ((m.corpus || {}).aggregate || {}).pairwise_f1 ?? null, tone: toneOf(i) }))}
        source="eval/corpus: hand-labelled, generated by a different program"
        span="11 scenarios, replayed through the real engine" note="the independent yardstick" />
      <${Curve} title="5 · Optimisation history — best validation loss so far" xLabel="fit, in order"
        yLabel="validation log loss" series=${curve((m) => bestSoFar((m.search || {}).trials || []))}
        source=${VALID} n="the same validation rows for every model"
        note="lower is better; a line that flattens early has found its best" />
      <${Curve} title="7 · ROC, all models" xLabel="false positive rate" yLabel="true positive rate"
        xRange=${[0, 1]} yRange=${[0, 1]} reference="diagonal"
        series=${curve((m) => (iidPairs(m).roc_curve || []).map(([f, t]) => [f, t]))}
        source=${GEN} n=${span} />
      <${Curve} title="7 · Precision–recall, all models" xLabel="recall" yLabel="precision"
        xRange=${[0, 1]} yRange=${[0, 1]}
        reference=${{ y: iidPairs(trained[0]).positive_rate_weighted }}
        series=${curve((m) => (iidPairs(m).pr_curve || []).map(([r, p]) => [r, p]))}
        source=${GEN} n=${span} note="dashed: the baseline positive rate" />
      <${Curve} title="8 · Prediction vs actual, all models" xLabel="predicted probability"
        yLabel="observed rate" xRange=${[0, 1]} yRange=${[0, 1]} reference="diagonal"
        series=${curve((m) => ((iidPairs(m).calibration || {}).bins || []).filter((b) => b[2] > 0).map(([p, o]) => [p, o]))}
        source=${GEN} n=${span} note="on the diagonal is honest" />
      <${Bars} title="9 · Mean |residual|, all models" unit="ratio"
        rows=${trained.map((m, i) => ({ key: m.ref, label: m.name,
          value: (iidPairs(m).residuals || {}).mean_abs ?? null, tone: toneOf(i) }))}
        source=${GEN} span=${span} note="lower is better: the average distance of p from the outcome" />
      <section class="chart-block mchart">
        <${Scatter} title="10 · Training time × performance"
          points=${trained.map((m, i) => ({ x: searchSeconds(m), y: meanF1(m), tone: toneOf(i) }))}
          xLabel="seconds to search and fit" yLabel="mean pairwise F1 (higher is better)"
          source="the training machine; the judge's offline score" n=${`${trained.length} models`} />
        <${Legend} series=${legend} />
      </section>
      <${Bars} title="10 · Scoring cost per pair on this appliance" unit="µs"
        rows=${trained.map((m, i) => ({ key: m.ref, label: m.name,
          value: (m.latency || {}).appliance_us ?? null, tone: toneOf(i) }))}
        source="measured at start-up on the packaged benchmark pairs" span="median of three passes"
        note="the fast loop's budget is the eligibility line on the league table" />
    </div>
  </div>`;
}

export function meanF1(model) {
  const values = suiteRows(model).map((r) => r.value).filter((v) => v != null);
  return values.length ? values.reduce((a, b) => a + b, 0) / values.length : null;
}

function searchSeconds(model) {
  const trials = (model.search || {}).trials || [];
  const search = trials.reduce((a, t) => a + (t.seconds || 0), 0);
  return search + ((model.final_fit || {}).seconds || 0);
}
